### ISSUE TITLE
how can i get the element style?``` 

### ISSUE THREAD

**Issue by cutemurphy2022** [yousufkalim/html-to-json#2]
because i need the style to get the element's width / height / transform / color etc..``

help me`

**Comment by yousufkalim** [comment]
Hi @cutemurphy2022, Hope you doing well.

    Thank you for reaching me out. Once you process your HTML through the HTMLParser method, as described in the documentation, you will get a result similar to this along with attributes, including the style.

```JavaScript
{
  "type": "div",
  "content": [
    {
      "type": "ul",
      "content": [
        {
          "type": "li",
          "content": [
            "Hello ",
            {
              "type": "strong",
              "content": [
                "World"
              ]
            }
          ]
        }
      ]
    }
  ],
  "attributes": {
    "style": "font-size: 20px; width: 80%; margin: auto"
  }
}
```

**Comment by yousufkalim** [comment]
You can also parse the style string by creating a function in the following way to create an object with properties and their values of the CSS:

```javascript
const parseStyle = (styleString) => {
  var styleObject = {};
  var styleProperties = styleString.split(";");

  styleProperties.forEach(function(property) {
    var parts = property.split(":");
    var key = parts[0].trim();
    var value = parts[1].trim();

    styleObject[key] = value;
  });

  return styleObject;
}

const styleString = "font-size: 20px; width: 80%; margin: auto";

console.log(parseStyle(styleString));
```

This will output the following object:

```javascript
{
  "font-size": "20px",
  "width": "80%",
  "margin": "auto"
}
```

**Comment by cutemurphy2022** [comment]
u r a nice guy ` thank you `` 

i have modify your code ``` because some style is not in the style `` maybe is render by the class

so i use the computedStyles to get the computed style ``

thank u ` u do the good job` :D
