### ISSUE TITLE
无法找到模块“html-to-json-parser”的声明文件

### ISSUE THREAD

**Issue by MiniJude** [yousufkalim/html-to-json#3]
`import { JSONType } from 'html-to-json-parser'`

无法找到模块“html-to-json-parser”的声明文件。“c:/code/demo-vue-quill/node_modules/html-to-json-parser/dist/index.modern.js”隐式拥有 "any" 类型。
  There are types at 'c:/code/demo-vue-quill/node_modules/html-to-json-parser/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'html-to-json-parser' library may need to update its package.json or typings.ts(7016)

**Comment by yousufkalim** [comment]
Hi @MiniJude, Thank you for reaching me out!

I need more clarification on this issue (e.g, environment where you running, type in pkg.json, is it client or server side script, main language of the project)

Thanks
Yousuf Kalim

**Comment by MiniJude** [comment]
> Hi @MiniJude, Thank you for reaching me out!
> 
> I need more clarification on this issue (e.g, environment where you running, type in pkg.json, is it client or server side script, main language of the project)
> 
> Thanks Yousuf Kalim

thank you for your reply!

`node -v v18.16.0`
and this is my package.json file:
```ts
// package.json
{
  "name": "vue-quill-demo",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@vueup/vue-quill": "^1.1.1",
    "@vueuse/core": "^10.1.2",
    "html-to-json-parser": "^1.1.0",
    "katex": "^0.16.7",
    "less": "^4.1.3",
    "quill-blot-formatter": "^1.0.5",
    "quill-image-uploader": "^1.3.0",
    "vue": "^3.2.47"
  },
  "devDependencies": {
    "@types/katex": "^0.16.0",
    "@vitejs/plugin-vue": "^4.1.0",
    "typescript": "^5.0.2",
    "vite": "^4.3.2",
    "vue-tsc": "^1.4.2"
  }
}
```

**Comment by olup** [comment]
probably related : `TypeError: (0 , html_to_json_parser_1.default) is not a function` - cannot import HTMLParser

**Comment by yousufkalim** [comment]
I am closing this issue as I have just updated the library to version `2.0.0`, where I fixed the issue by moving the function from default export to normal export.

Please update the library and follow the Readme.md for revised implementation.

Thank You

**Comment by nienkeboomsma** [comment]
I am having the same issue on 2.0.1:

> Could not find a declaration file for module 'html-to-json-parser'. '/Users/Nienke/Sites/dokugaku/node_modules/.pnpm/html-to-json-parser@2.0.1/node_modules/html-to-json-parser/dist/index.modern.js' implicitly has an 'any' type.
> There are types at '/Users/Nienke/Sites/dokugaku/services/work-processor/node_modules/html-to-json-parser/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'html-to-json-parser' library may need to update its package.json or typings.ts(7016)

Pertinent parts of `package.json`

```
{
  "exports": "./index.js",
  "type": "module",
  "engines": {
    "node": ">=16"
  },
  "dependencies": {
    "html-to-json-parser": "^2.0.1",
  },
}
```

`tsconfig.json`

```
{
  "extends": "@repo/typescript-config/base.json",
  "compilerOptions": {
    "lib": ["ES2021"],
    "outDir": "./dist",
    "rootDir": "./src",
    "module": "node16",
    "moduleResolution": "node16"
  },
  "exclude": ["node_modules"],
  "include": ["src"]
}
```

`@repo/typescript-config/base.json`
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "incremental": false,
    "isolatedModules": true,
    "lib": ["es2022", "DOM", "DOM.Iterable"],
    "module": "NodeNext",
    "moduleDetection": "force",
    "moduleResolution": "NodeNext",
    "noUncheckedIndexedAccess": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ES2022"
  }
}
```
